version: '3.4'

services:
    postgresql_database:
      image: postgres:latest
      environment: 
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=Test
      ports: 
        - "5432:5432"
      restart: unless-stopped
      volumes: 
        - database-data:/var/lib/postgresql/data/
    pgadmin:
      images: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports: 
        - "5050:80"
      restart: unless-stopped
      volumes: 
        - pgadmin:/root/.pgadmin
volumes: 
  database-data:
  pgadmin: